#############################################################################
# Makefile for building: FCD-1
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  FCD-1.pro
# Template: app
# Command: /home/msil/Qt5.3.1/5.3/gcc/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile FCD-1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_SERIALPORT_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I. -I/home/msil/Qt5.3.1/5.3/gcc/include -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQml -I/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort -I/home/msil/Qt5.3.1/5.3/gcc/include/QtNetwork -I/home/msil/Qt5.3.1/5.3/gcc/include/QtGui -I/home/msil/Qt5.3.1/5.3/gcc/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/msil/Qt5.3.1/5.3/gcc -Wl,-rpath,/home/msil/Qt5.3.1/5.3/gcc/lib
LIBS          = $(SUBLIBS) -L/home/msil/Qt5.3.1/5.3/gcc/lib -lQt5Quick -lQt5Qml -lQt5Widgets -lQt5SerialPort -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/msil/Qt5.3.1/5.3/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		circleprogress.cpp \
		console.cpp \
		serial.cpp qrc_qml.cpp \
		moc_circleprogress.cpp \
		moc_serial.cpp \
		moc_console.cpp
OBJECTS       = main.o \
		circleprogress.o \
		console.o \
		serial.o \
		qrc_qml.o \
		moc_circleprogress.o \
		moc_serial.o \
		moc_console.o
DIST          = /home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf \
		deployment.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qml_debug.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/declarative_debug.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/unix/opengl.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/uic.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf \
		FCD-1.pro main.cpp \
		circleprogress.cpp \
		console.cpp \
		serial.cpp
QMAKE_TARGET  = FCD-1
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = FCD-1


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FCD-1.pro /home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf /home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf \
		deployment.pri \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qml_debug.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/declarative_debug.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/unix/opengl.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/uic.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf \
		/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf \
		FCD-1.pro \
		qml.qrc \
		/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Quick.prl \
		/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Qml.prl \
		/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Network.prl \
		/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Core.prl \
		/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Gui.prl \
		/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Widgets.prl \
		/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5SerialPort.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile FCD-1.pro
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf:
deployment.pri:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qml_debug.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/declarative_debug.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/unix/opengl.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/uic.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf:
/home/msil/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf:
FCD-1.pro:
qml.qrc:
/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Quick.prl:
/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Qml.prl:
/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Network.prl:
/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Core.prl:
/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Gui.prl:
/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5Widgets.prl:
/home/msil/Qt5.3.1/5.3/gcc/lib/libQt5SerialPort.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile FCD-1.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/FCD-11.0.0 || mkdir -p .tmp/FCD-11.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/FCD-11.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/FCD-11.0.0/ && $(COPY_FILE) --parents circleprogress.h serial.h console.h .tmp/FCD-11.0.0/ && $(COPY_FILE) --parents main.cpp circleprogress.cpp console.cpp serial.cpp .tmp/FCD-11.0.0/ && (cd `dirname .tmp/FCD-11.0.0` && $(TAR) FCD-11.0.0.tar FCD-11.0.0 && $(COMPRESS) FCD-11.0.0.tar) && $(MOVE) `dirname .tmp/FCD-11.0.0`/FCD-11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FCD-11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		Speed_DialView.qml \
		DialDelegate.qml \
		PointerDelegate.qml \
		RPM_DialView.qml \
		Listitem.qml \
		ListmenuDelegate.qml \
		ListitemDelegate.qml \
		BackgrouldDelegate.qml \
		Listmenu.qml \
		DialView.qml \
		StartstopButton.qml \
		Pathview_menu.qml \
		BackgroundView.qml \
		PointerView.qml \
		main.qml \
		image/exhaust.png \
		image/immobilizer.png \
		image/toolbar.png \
		image/RPM_01.png \
		image/Pointer5.png \
		image/Skin_Blank_FG_Dial2.png \
		image/Skin_Blank_RPM_Dial2.png \
		image/blue.jpg \
		image/battery_low.png \
		image/Skin_Blank_RPM_Dial.png \
		image/Pointer3.png \
		image/clear.png \
		image/Skin_3_Speedo_Dial.png \
		image/oilIndicator.png \
		image/Engine_start_stop_active.png \
		image/Skin_Blank_FG_Dial.png \
		image/grass.jpg \
		image/logo.png \
		image/Skin_6.png \
		image/speed_active1.png \
		image/PARKING.png \
		image/Skin_Blank_Speedo_RPM_Pointer3.png \
		image/battery_med.png \
		image/Pointer1.png \
		image/Skin_9_RPM_Pointer4.png \
		image/Highbeam.png \
		image/Skin_Blank_Speedo_Dial2.png \
		image/Skin_4.png \
		image/Skin_3_Graphic.png \
		image/Skin_15.png \
		image/Skin_9_Speedo2.png \
		image/low_oil.png \
		image/neutral.png \
		image/low_aux_air.png \
		image/Skin_9_RPM_Pointer2.png \
		image/Skin_Blank_Speedo_Dial.png \
		image/Skin_Blank_TG_Dial.png \
		image/ABS.png \
		image/Skin_3_Graphic2.png \
		image/overlay_active.png \
		image/Skin_11.png \
		image/Skin_9_FG_TG2.png \
		image/glow_plug.png \
		image/parkingLight.png \
		image/Skin_Blank_Gauge_Pointer3.png \
		image/brown.jpg \
		image/High_Beam_Indicator.png \
		image/Skin_3_FG_Dial2.png \
		image/hay.jpg \
		image/Skin_9_Temp_Blank_Patch.png \
		image/Skin_9_RPM1.png \
		image/engine_check.png \
		image/rpm_active.png \
		image/petrol.png \
		image/Skin_3_FG_Dial.png \
		image/Skin_3_RPM_Dial.png \
		image/Oil.png \
		image/Skin_Blank_TG_Dial2.png \
		image/filter.png \
		image/Pointer6.png \
		image/dropDown.png \
		image/disconnect.png \
		image/Skin_9_Speedo.png \
		image/navigation_next_item.png \
		image/Skin_9.png \
		image/cabin_lock.png \
		image/battery_full.png \
		image/Skin_9_FG_TG.png \
		image/turn_indicator.png \
		image/Brake_failure.png \
		image/Pointer4.png \
		image/Skin_7.png \
		image/Skin_3_TG_Dial.png \
		image/rear_fog.png \
		image/Engine_start_stop_inactive.png \
		image/trans_1.png \
		image/dc_dc_fail.png \
		image/Skin_9_RPM.png \
		image/Pointer2.png \
		image/Skin_9_RPM_Pointer5.png \
		image/application-exit.png \
		image/water_in_fuel.png \
		image/Skin_16.png \
		image/tabs_standard.png \
		image/Skin_Blank_Speedo_RPM_Pointer2.png \
		image/Skin_9_RPM_Pointer3.png \
		image/Speedo_01.png \
		image/speed_inactive.png \
		image/Skin_14.png \
		image/Skin_9_Speedo1.png \
		image/stop_engine.png \
		image/rpm_active1.png \
		image/Skin_Blank_Gauge_Pointer.png \
		image/Skin_9_RPM_Pointer1.png \
		image/car.png \
		image/button_default.png \
		image/Red.jpg \
		image/Skin_3_RPM_Dial2.png \
		image/turn_indicator_left.png \
		image/overlay_active1.png \
		image/overlay_inactive1.png \
		image/navigation_previous_item.png \
		image/fuel_gauge.png \
		image/textinput.png \
		image/tab_selected.png \
		image/Skin_Blank_Graphic.png \
		image/connect.png \
		image/Temp_Col.png \
		image/Skin_3_TG_Dial2.png \
		image/Skin_9_FG_TG1.png \
		image/Skin_Blank_Speedo_RPM_Pointer.png \
		image/Skin_9_RPM2.png \
		image/MIL.png \
		image/Skin_Blank_Graphic2.png \
		image/Skin_9_Speedo_Blank_Patch.png \
		image/button_pressed.png \
		image/Skin_Blank_Gauge_Pointer2.png \
		image/Skin_3_Speedo_Dial2.png \
		image/battery_low1.png \
		image/settings.png \
		image/rpm_inactive.png \
		image/Pointer7.png \
		image/Skin_9_RPM_Black_Patch.png
	/home/msil/Qt5.3.1/5.3/gcc/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_circleprogress.cpp moc_serial.cpp moc_console.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_circleprogress.cpp moc_serial.cpp moc_console.cpp
moc_circleprogress.cpp: /home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/QQuickPaintedItem \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qquickpainteditem.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qquickitem.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qtquickglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqml.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlprivate.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qtqmlglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlparserstatus.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlpropertyvaluesource.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmllist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetaobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlcomponent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlerror.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qjsvalue.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/QList \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qaccessible.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/QPainter \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainter.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmath.h \
		circleprogress.h
	/home/msil/Qt5.3.1/5.3/gcc/bin/moc $(DEFINES) -I/home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I'/home/msil/Target_Board/Yocto_BSP/Qt5_Creator_Examples/Switesh/Github_Repository_Switesh/FCD-1/10.Commits on Jan 30, 2015' -I/home/msil/Qt5.3.1/5.3/gcc/include -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQml -I/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort -I/home/msil/Qt5.3.1/5.3/gcc/include/QtNetwork -I/home/msil/Qt5.3.1/5.3/gcc/include/QtGui -I/home/msil/Qt5.3.1/5.3/gcc/include/QtCore circleprogress.h -o moc_circleprogress.cpp

moc_serial.cpp: /home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QMainWindow \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qicon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/QSerialPort \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/qserialport.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/qserialportglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		serial.h
	/home/msil/Qt5.3.1/5.3/gcc/bin/moc $(DEFINES) -I/home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I'/home/msil/Target_Board/Yocto_BSP/Qt5_Creator_Examples/Switesh/Github_Repository_Switesh/FCD-1/10.Commits on Jan 30, 2015' -I/home/msil/Qt5.3.1/5.3/gcc/include -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQml -I/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort -I/home/msil/Qt5.3.1/5.3/gcc/include/QtNetwork -I/home/msil/Qt5.3.1/5.3/gcc/include/QtGui -I/home/msil/Qt5.3.1/5.3/gcc/include/QtCore serial.h -o moc_serial.cpp

moc_console.cpp: /home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QPlainTextEdit \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qplaintextedit.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qtextedit.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qframe.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextdocument.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextformat.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qabstracttextdocumentlayout.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextlayout.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qglyphrun.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrawfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontdatabase.h \
		console.h
	/home/msil/Qt5.3.1/5.3/gcc/bin/moc $(DEFINES) -I/home/msil/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I'/home/msil/Target_Board/Yocto_BSP/Qt5_Creator_Examples/Switesh/Github_Repository_Switesh/FCD-1/10.Commits on Jan 30, 2015' -I/home/msil/Qt5.3.1/5.3/gcc/include -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick -I/home/msil/Qt5.3.1/5.3/gcc/include/QtQml -I/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort -I/home/msil/Qt5.3.1/5.3/gcc/include/QtNetwork -I/home/msil/Qt5.3.1/5.3/gcc/include/QtGui -I/home/msil/Qt5.3.1/5.3/gcc/include/QtCore console.h -o moc_console.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /home/msil/Qt5.3.1/5.3/gcc/include/QtGui/QGuiApplication \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qguiapplication.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qinputmethod.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/QQmlApplicationEngine \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlapplicationengine.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlengine.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qjsengine.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qjsvalue.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qtqmlglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlerror.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmldebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlcontext.h \
		circleprogress.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/QQuickPaintedItem \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qquickpainteditem.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qquickitem.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qtquickglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqml.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlprivate.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlparserstatus.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlpropertyvaluesource.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmllist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetaobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlcomponent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/QList \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qaccessible.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/QPainter \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainter.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmath.h \
		serial.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QMainWindow \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qicon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/QSerialPort \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/qserialport.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/qserialportglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QApplication \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qapplication.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qdesktopwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

circleprogress.o: circleprogress.cpp circleprogress.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/QQuickPaintedItem \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qquickpainteditem.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qquickitem.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQuick/qtquickglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqml.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlprivate.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qtqmlglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlparserstatus.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlpropertyvaluesource.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmllist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetaobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlcomponent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qqmlerror.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtQml/qjsvalue.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/QObject \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/QList \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qaccessible.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/QPainter \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainter.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o circleprogress.o circleprogress.cpp

console.o: console.cpp console.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QPlainTextEdit \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qplaintextedit.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qtextedit.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qframe.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextdocument.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextformat.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qabstracttextdocumentlayout.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextlayout.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qglyphrun.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrawfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontdatabase.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QScrollBar \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qscrollbar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractslider.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o console.o console.cpp

serial.o: serial.cpp serial.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QMainWindow \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qicon.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/QSerialPort \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/qserialport.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/qserialportglobal.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/QSerialPortInfo \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtSerialPort/qserialportinfo.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/QIntValidator \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qvalidator.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtCore/qregularexpression.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QLineEdit \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qlineedit.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qframe.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextcursor.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextformat.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QMessageBox \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qmessagebox.h \
		console.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/QPlainTextEdit \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qplaintextedit.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qtextedit.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextdocument.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qabstracttextdocumentlayout.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qtextlayout.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qglyphrun.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qrawfont.h \
		/home/msil/Qt5.3.1/5.3/gcc/include/QtGui/qfontdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial.o serial.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_circleprogress.o: moc_circleprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_circleprogress.o moc_circleprogress.cpp

moc_serial.o: moc_serial.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serial.o moc_serial.cpp

moc_console.o: moc_console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_console.o moc_console.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/FCD-1/bin || mkdir -p $(INSTALL_ROOT)/opt/FCD-1/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/FCD-1/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/FCD-1/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/FCD-1/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

